# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)

# NeoForge
neo_version=21.1.230
neo_version_range=[21.1.230,)

# Mod
mod_id=mespawner
mod_name=MESpawner
mod_version=0.2.0
mod_authors=YourName
mod_description=An AE2 addon that adds an ME-powered mob spawner.
mod_license=MIT

# Loader
loader_version_range=[4,)

# Java
java_version=21
